### PR TITLE
fixed CssPrinter pretty print indent levels

### LINKED ISSUE #762: pretty print does not render media query block correctly
Pretty print mode seems to ignore `@media` query blocks

The following:

```
.good { color: red; }
@media screen { .better { color: blue; } }
.best { color: green }
```

should generate:

```
.good {
  color: #f00;
}
@media screen {
  .better {
    color: #00f;
  }
}
.best {
  color: #008000;
}
```

although for now it generates:

```
.good {
  color: #f00;
} @media screen {
.better {
  color: #00f;
}
}
.best {
  color: #008000;
}
```

Unit test [here](https://github.com/tekartik/yacht.dart/blob/c207e0f6c5bc1750b0258fccb1d25cfd852a1d86/test/csslib_utils_test.dart#L189-L218)

### PR DESCRIPTION
**Pull request by devoncarew**
- updated the pretty-print impl. of `CssPrinter` to better calculate indent levels
- fix https://github.com/dart-lang/tools/issues/762

This fixes how indents are calculated when pretty-printing css. Previously all properties were hard-coded to being indented by 2 spaces. Now, we increment and decrement the indent level based on opening and closing braces.

### CODE REVIEW

File: lib/src/css_printer.dart [hunk 1]
```diff
@@ -201,101 +262,106 @@ class CssPrinter extends Visitor {
...
-    emit('}');
+    _emitRBrace();
   }
 
   @override
   void visitFontFaceDirective(FontFaceDirective node) {
-    emit('$_newLine@font-face ');
-    emit('$_sp{$_newLine');
+    emit('@font-face ');
+    emit(_sp);
```
Comment (leonsenft) [inline lib/src/css_printer.dart]: I think there's an extra/unnecessary space here. I'm guessing this was unintentional in the original code.

File: lib/src/css_printer.dart [hunk 2]
```diff
@@ -201,101 +262,106 @@ class CssPrinter extends Visitor {
...
       ruleset.visit(this);
     }
-    emit('}');
+    _emitRBrace();
   }
 
   @override
   void visitMixinDeclarationDirective(MixinDeclarationDirective node) {
-    emit('@mixin ${node.name} {\n');
+    emit('@mixin ${node.name} ');
```
Comment (leonsenft) [inline lib/src/css_printer.dart]: This trailing space can be a `_sp`.

File: lib/src/css_printer.dart [hunk 3]
```diff
@@ -7,35 +7,89 @@ part of '../visitor.dart';
...
+    } else {
+      _buff.write(str);
+    }
+  }
+
+  void _emitLBrace() {
+    if (_prettyPrint) {
+      _buff.write('{\n');
+      _startOfLine = true;
+      _indent += 2;
```
Comment (leonsenft) [inline lib/src/css_printer.dart]: nit: Since the else branch is a subset of the if branch, we can just extract the common parts outside the if-else:

```dart
_indent += 2;
_buff.write('{');

if (_prettyPrint) {
  _buff.writeln();
  _startOfLine = true;
}
```

File: lib/src/css_printer.dart [hunk 4]
```diff
@@ -7,35 +7,89 @@ part of '../visitor.dart';
...
+      _buff.write(';');
+      if (forceLf) _buff.write('\n');
+    }
+  }
+
+  void _emitLf({bool force = false}) {
+    if (_prettyPrint) {
+      _buff.write('\n');
+      _startOfLine = true;
+    } else {
```
Comment (leonsenft) [inline lib/src/css_printer.dart]: nit : combine into `else if`

File: lib/src/css_printer.dart [hunk 5]
```diff
@@ -7,35 +7,89 @@ part of '../visitor.dart';
...
+      _indent += 2;
+      _buff.write('{');
+    }
+  }
+
+  void _emitRBrace() {
+    if (_prettyPrint) {
+      if (!_startOfLine) _buff.write('\n');
+      _indent -= 2;
```
Comment (leonsenft) [inline lib/src/css_printer.dart]: Same thing for the indent update statement here.

File: lib/src/css_printer.dart [hunk 6]
```diff
@@ -7,35 +7,89 @@ part of '../visitor.dart';
...
+      _buff.write('${' ' * _indent}}\n');
+      _startOfLine = true;
+    } else {
+      _indent -= 2;
+      _indent == 0 ? _buff.write('}\n') : _buff.write('}');
```
Comment (leonsenft) [inline lib/src/css_printer.dart]: Using the ternary expression for side-effects (as opposed to a value) is uncommon. Consider extracting the common part, and adding a simple if-statement.

```dart
_buff.write('}');
if (_ident == 0) {
  _buff.writeln();
}
```

**Review by leonsenft — CHANGES_REQUESTED** [review]

File: lib/src/css_printer.dart (hunk 3 above)
Comment (devoncarew) [reply lib/src/css_printer.dart]: 👍 - done

File: lib/src/css_printer.dart (hunk 5 above)
Comment (devoncarew) [reply lib/src/css_printer.dart]: done

File: lib/src/css_printer.dart (hunk 6 above)
Comment (devoncarew) [reply lib/src/css_printer.dart]: done

File: lib/src/css_printer.dart (hunk 4 above)
Comment (devoncarew) [reply lib/src/css_printer.dart]: done

File: lib/src/css_printer.dart (hunk 2 above)
Comment (devoncarew) [reply lib/src/css_printer.dart]: done

File: lib/src/css_printer.dart (hunk 1 above)
Comment (devoncarew) [reply lib/src/css_printer.dart]: ah, yup; I'll remove one of these

**Review by devoncarew — COMMENTED** [review]
Ptal - updated.

**Review by leonsenft — APPROVED** [review]
