### PR TITLE
Fixed a crashed caused by wrong numbers parsing of selector expressions

### LINKED ISSUE #92: Unhandled exception: Class 'int' has no instance getter 'name'.
csslib throws an unhandled error when parsing the following CSS.

Here's the stacktrace:

```
Unhandled exception:
NoSuchMethodError: Class 'int' has no instance getter 'name'.
Receiver: 0
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Parser.processSelectorExpression (package:csslib/parser.dart:1690:47)
#2      _Parser.processPseudoSelector (package:csslib/parser.dart:1605:20)
#3      _Parser.simpleSelectorTail (package:csslib/parser.dart:1545:16)
#4      _Parser.simpleSelector (package:csslib/parser.dart:1490:14)
#5      _Parser.simpleSelectorSequence (package:csslib/parser.dart:1403:11)
#6      _Parser.processSelector (package:csslib/parser.dart:1338:26)
#7      _Parser.processSelectorGroup (package:csslib/parser.dart:1320:27)
#8      _Parser._nestedSelector (package:csslib/parser.dart:1152:30)
#9      _Parser.processDeclarations (package:csslib/parser.dart:1181:27)
#10     _Parser.processRule (package:csslib/parser.dart:1105:37)
#11     _Parser.parse (package:csslib/parser.dart:206:20)
#12     parse (package:csslib/parser.dart:99:32)
#13     parseCss (package:linkcheck/src/parsers/css.dart:29:17)
```

Here's the exact CSS. Sorry for the huge blob, I'm currently not in position to try to minimize the repro.

[csslib-throws.css.zip](https://github.com/dart-lang/csslib/files/3224786/csslib-throws.css.zip)

### LINKED ISSUE #1168: Unhandled exception: Class 'int' has no instance getter 'name'.
csslib throws an unhandled error when parsing the following CSS.

Here's the stacktrace:

```
Unhandled exception:
NoSuchMethodError: Class 'int' has no instance getter 'name'.
Receiver: 0
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
dart-lang/tools#747      _Parser.processSelectorExpression (package:csslib/parser.dart:1690:47)
dart-lang/tools#748      _Parser.processPseudoSelector (package:csslib/parser.dart:1605:20)
dart-lang/tools#749      _Parser.simpleSelectorTail (package:csslib/parser.dart:1545:16)
dart-lang/tools#750      _Parser.simpleSelector (package:csslib/parser.dart:1490:14)
dart-lang/tools#751      _Parser.simpleSelectorSequence (package:csslib/parser.dart:1403:11)
dart-lang/tools#752      _Parser.processSelector (package:csslib/parser.dart:1338:26)
dart-lang/tools#753      _Parser.processSelectorGroup (package:csslib/parser.dart:1320:27)
dart-lang/tools#754      _Parser._nestedSelector (package:csslib/parser.dart:1152:30)
dart-lang/tools#755      _Parser.processDeclarations (package:csslib/parser.dart:1181:27)
dart-lang/tools#756     _Parser.processRule (package:csslib/parser.dart:1105:37)
dart-lang/tools#757     _Parser.parse (package:csslib/parser.dart:206:20)
dart-lang/csslib#12     parse (package:csslib/parser.dart:99:32)
dart-lang/csslib#13     parseCss (package:linkcheck/src/parsers/css.dart:29:17)
```

Here's the exact CSS. Sorry for the huge blob, I'm currently not in position to try to minimize the repro.

[csslib-throws.css.zip](https://github.com/dart-lang/csslib/files/3224786/csslib-throws.css.zip)

### PR DESCRIPTION
**Pull request by sjbanov**
Closes dart-lang/tools#1168

We can use logic from processDimension function which already process various types of expressions.

### CODE REVIEW

File: test/compiler_test.dart [hunk 1]
```diff
@@ -727,6 +727,18 @@ void testEmitter() {
...
+  var errors = <Message>[];
+  var input = '.foobar {'
+      'border-radius: calc(0 - 1px);'
+      'border-width: calc(0 + 1px);'
+      '}';
+  var stylesheet = parseCss(input, errors: errors);
+
+  expect(stylesheet != null, true);
+  expect(errors.isEmpty, true, reason: errors.toString());
+}
```
Comment (leonsenft) [inline test/compiler_test.dart:749]: Can you please test that the `prettyPrint(stylesheet)` output is as expected here (to make sure we're not dropping anything when parsing). See the previous test case above for an example.

File: test/compiler_test.dart [hunk 2]
```diff
@@ -744,4 +756,5 @@ main() {
   test('stringEscape', testStringEscape);
   test('Parse List<int> as input', testArrayOfChars);
   test('Simple Emitter', testEmitter);
+  test('Selector Expression Parsing', testSelectorExpressionParsing);
```
Comment (leonsenft) [inline test/compiler_test.dart]: This is a bit of a misnomer. While yes, this does exercise the selector expression path (until it bails out because it isn't a selector), it's really just ensuring that the selector expression doesn't throw before declaration expression parsing occurs. I'd suggest renaming to just "Expression parsing" and `testExpressionParsing`.

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,7 @@
+## 0.16.1
+	
+* Fixed a crashed caused by wrong numbers parsing of selector expressions
```
Comment (leonsenft) [inline CHANGELOG.md]: This message could be a little more concrete, how about:

> Fixed a crash caused by parsing certain `calc()` expressions and variables names that contain numbers.

**Review by leonsenft — CHANGES_REQUESTED** [review]
Thank you for persevering on this and finding another solution!

Overall looks great, a few minor suggestions. But first, could you please rebase your first commit onto the up to date `master` branch to avoid the merge commit? I'd like to keep the commit history free of a merge.

File: test/compiler_test.dart (hunk 1 above)
Comment (sjbanov) [reply test/compiler_test.dart:749]: Fixed

File: test/compiler_test.dart (hunk 2 above)
Comment (sjbanov) [reply test/compiler_test.dart]: Fixed

File: CHANGELOG.md (hunk 3 above)
Comment (sjbanov) [reply CHANGELOG.md]: Fixed

**Comment by sjbanov** [comment]
Thank you for your quick reaction, detailed comments and fix suggestions!
I can squash all commits and rebase them on the top of the master branch to keep clean git history.
But unfortunately we are still use Angular 5.0.0 and we need a patch for csslib on version 0.14.6 (for example 0.14.6+1).
Is it possible to publish patch? How can I do that right?

**Comment by leonsenft** [comment]
Thanks for addressing those comments!

A rebase would still be preferable to a squash, at least to keep the refactors you made separate from the fixes. You should be able to do an interactive rebase to easily drop the merge commit and keep the rest.

If you've not comfortable doing the rebase, I can do it, but you'll have to give me access so I can update this PR: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by sjbanov** [comment]
I understand your point about rebasing. I can do that.

But first could you clarify how to create a patch?
I started branch from 0.14.6 tag plus one commit with tests fix because I want to be published version 0.14.6+1 with this fix in global central. How to do that?

**Comment by leonsenft** [comment]
Ah I see. Sorry I didn't address your question about publishing a version compatible with Angular 5.0.0. So typically we don't bother backporting minor fixes like this.

Can I ask if updating to Angular 5.3.0 is possible for your project? That bumps the dependency on csslib to ^0.16.0 so it would pick up this fix.

Alternatively, you could use a [git dependency](https://dart.dev/tools/pub/dependencies#git-packages) override in your project's pubspec.yaml:

```yaml
dependency_overrides:
  csslib:
    git:
      url: git://github.com/sjbanov/csslib.git
      ref: your-patch
```

If neither of these solutions are realistic for your project, you'll need to create two separate pull requests.
- One based on `v0.14.6` with the fix. This we won't merge, but could use to publish the backport.
- One based on the latest `master` commit. This we'll use to merge the fix and publish as 0.16.1.

**Comment by sjbanov** [comment]
Thanks for your clarify!

I have done cleaning up on this branch. Now there are only two commits. One with the main fix. And the second with refactors.

Also I have created the branch (https://github.com/sjbanov/csslib/tree/fix-selector-expr-parsing-patch) with Angular 5.0.0 compatible fix. In my company there is too complex dependency control. And unfortunately we can not migrate on latest Angular right now. It would be great if you publish backport.

**Comment by sjbanov** [comment]
@leonsenft Could we continue this MR? Or do you have any doubt about that?

**Review by leonsenft — APPROVED** [review]

**Comment by leonsenft** [comment]
Sorry for the slow response, I was on vacation.

Thanks for cleaning up the commits! Now that the fix is a single commit, I think I can just cherry pick that commit into a new branch and publish that. I'll let you know when I've published both.

**Comment by leonsenft** [comment]
I've published this as 0.16.1 and the backported fix as 0.14.6+1: https://pub.dev/packages/csslib/versions.

Thanks for your help!
